server:
    port: 8765

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000
ribbon:
    ConnectTimeout: 10000
    ReadTimeout: 20000  

spring:
    application:
        name: api-gateway-zuul

zuul:
  routes:
    cadastro:
        service-id: ms-cadastro
        path: /ms-cadastro/**
    leitura:
        service-id: ms-leitura
        path: /ms-leitura/**
    notificacao:
        service-id: ms-notificacao
        path: /ms-notificacao/**